# Generated by Django 4.2.6 on 2023-10-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notogri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_soz', models.CharField(max_length=255)),
                ('t_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Togri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_soz', models.CharField(max_length=255)),
            ],
        ),
    ]
